# Generated by Django 4.2.4 on 2023-08-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmusicArtists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(to='appmusicArtists.genre'),
        ),
    ]
